apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: inventory-service
          image: ghcr.io/devgeniussourav/commerceflow-inventory-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/commerceflow_inventory?options=-c%20TimeZone=Asia/Kolkata
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
              value: "true"