apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: payment-service
          image: ghcr.io/devgeniussourav/commerceflow-payment-service:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: payment-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_KAFKA_LISTENER_AUTO_STARTUP
              value: "true"