apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product-service
          image: ghcr.io/devgeniussourav/commerceflow-product-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/commerceflow_product?options=-c%20TimeZone=Asia/Kolkata
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root