apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: commerceflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product-service
          image: ghcr.io/devgeniussourav/commerceflow-product-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: product-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-db-secret
                  key: SPRING_DATASOURCE_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"