apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: commerceflow
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/commerceflow_user?options=-c%20TimeZone=Asia/Kolkata
  SPRING_DATASOURCE_USERNAME: postgres
