server:
  port: 8083

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/commerceflow_inventory?connectionTimeZone=UTC
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    show-sql: false

    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{correlationId}] %logger - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true